import { Router } from "express";
import { SpecialtyRoute } from "../modules/Specialty/specialty.route";
import { AuthRoute } from "../modules/auth/auth.route";
import { userRouters } from "../modules/user/user.route";
import { doctorRouters } from "../modules/doctor/doctor.route";
import { AdminRoutes } from "../modules/admin/admin.route";
import { scheduleRoutes } from "../modules/schedule/schedule.route";
import { DoctorScheduleRoutes } from "../modules/doctorSchedule/doctorSchedule.route";
import { AppointmentRoutes } from "../modules/appointment/appointment.route";

const router = Router();
router.use("/auth", AuthRoute);
router.use("/specialty", SpecialtyRoute);
router.use("/users", userRouters);
router.use("/doctors", doctorRouters);
router.use("/admin", AdminRoutes);
router.use("/schedules", scheduleRoutes);
router.use("/doctor-schedules", DoctorScheduleRoutes);
router.use("/appointment", AppointmentRoutes);
export const IndexRoute = router;
